[build]
  command = "npm run build-production"
  publish = "dist/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self';"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy	= "no-referrer"

[[headers]]
  for = "/{main,manifest,runtime,vendors,workbox,xsl,icon_}*.{js,json,svg}"
  [headers.values]
	cache-control = "public, max-age=31536000, immutable"
